export const actionEnums = {
    SUBMIT_LOGIN_REQUEST: 'SUBMIT_LOGIN_REQUEST',
    SUBMIT_LOGIN_SUCCEED: 'SUBMIT_LOGIN_SUCCEED',
    SUBMIT_LOGIN_FAILURE: 'SUBMIT_LOGIN_FAILURE',
    GET_ALL_NOTES_REQUEST: 'GET_ALL_NOTES_REQUEST',
    GET_ALL_NOTES_SUCCEED: 'GET_ALL_NOTES_SUCCEED',
    GET_ALL_NOTES_FAILURE: 'GET_ALL_NOTES_FAILURE',
    ADD_NOTE_REQUEST: 'ADD_NOTE_REQUEST',
    ADD_NOTE_SUCCEED: 'ADD_NOTE_SUCCEED',
    ADD_NOTE_FAILURE: 'ADD_NOTE_FAILURE',
    DELETE_NOTE_REQUEST: 'DELETE_NOTE_REQUEST',
    DELETE_NOTE_SUCCEED: 'DELETE_NOTE_SUCCEED',
    DELETE_NOTE_FAILURE: 'DELETE_NOTE_FAILURE'
};